brutus/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path
from tcgen import views as tviews

from landing import views


admin.autodiscover()

urlpatterns = [
    url(r'^$', views.land, name='land'),
    url(r'^tcgen/$', tviews.create_tc, name="tcgen"),
    url(r'^subs/$', views.submissions, name="submissions"),
    url(r'^extend_dl/(?P<lab>[\w\-]+)/$$', views.ExtendDeadlineView.as_view(), name="extend_dl"),
    url(r'^lab_subs/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/(?P<lab>[\w\-]+)/$',
        views.lab_subs, name="lab_subs"),
    url(r'^home/$', views.home, name='home'),
    url(r'^404/$', views.test_404, name='test_404'),
    url(r'^ide/$', views.ide, name='ide'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_course/', login_required(views.AddCourseView.as_view()), name='add_course'),
    url(r'^edit_course/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/$',
        login_required(views.EditCourseView.as_view()), name='edit_course'),
    url(r'^course/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/$',
        views.course_detail, name='course_detail'),
    url(r'^lab/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/(?P<lab>[\w\-]+)/$',
        views.lab_detail, name='lab_detail'),
    url(r'^list_course/', login_required(views.ListCourseView.as_view()),
        name='list_course'),
    path('admin/', admin.site.urls),
    url(r'^logout/$', auth_views.LogoutView.as_view(
        template_name="registration/login.html"), name='logout'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^teach/(?P<teacher>[\w\-]+)/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/$',
        views.teach_course, name='teach'),
    url(r'^rm_std/(?P<student>[\w\-]+)/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/$',
        views.remove_student, name='remove_student'),
    url(r'^rm_ta/(?P<assistant>[\w\-]+)/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/$',
        views.remove_assistant, name='remove_ta'),
    url(r'^leave/(?P<teacher>[\w\-]+)/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/$',
        views.leave_course, name='leave'),
    url(r'^add_lab/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/$',
        login_required(views.AddLabView.as_view()), name='add_lab'),
    url(r'^add_problem/(?P<course>[\w\-]+)/(?P<session>[\w\-]+)/(?P<lab>[\w\-]+)/$',
        login_required(views.AddProblemView.as_view()), name='add_problem'),
    url(r'^solve/(?P<problem>[\w\-]+)/$',
        views.solve, name='solve'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

landing/models.py
import datetime
import os
import uuid

from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Profile(models.Model):
    class Meta:
        ordering = ('user',)
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.URLField(null=True, blank=True,
                             help_text='Profile picture URL')
    avatar_small = models.URLField(
        null=True, blank=True, help_text='Profile picture smaller URL')

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)

    @property
    def roll_no(self):
        return self.user.email.split('@')[0]


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


def current_year():
    return datetime.date.today().year


class Session(models.Model):
    class Meta:
        ordering = ('type',)
        verbose_name = 'Session'
        verbose_name_plural = 'Session'
        unique_together = ("type", "year")

    SESSION_CHOICES = (
        ('a', 'Autumn'),
        ('w', 'Winter'),
    )

    type = models.CharField(max_length=20, choices=SESSION_CHOICES)
    year = models.IntegerField(default=current_year, validators=[
        MinValueValidator(current_year()),
        MaxValueValidator(2100)
    ])

    def __str__(self):
        sessions = {'a': 'Autumn', 'w': 'Winter'}
        return sessions[self.type] + "-" + str(self.year)


class Course(models.Model):
    class Meta:
        ordering = ('name',)
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'
        unique_together = ("code", "session")

    name = models.CharField(max_length=50)
    code = models.CharField(max_length=5)
    session = models.ForeignKey(Session, on_delete=models.CASCADE,
                                help_text="Session when this course is to be taught")
    target_batch = models.IntegerField(help_text="Year when target batch will graduate", default=2020, validators=[
        MinValueValidator(2019),
        MaxValueValidator(2104)])

    def __str__(self):
        return str(self.session) + " " + self.name


class Student(models.Model):
    class Meta:
        ordering = ('profile',)
        verbose_name = 'Student'
        verbose_name_plural = 'Students'

    BRANCH_CHOICES = (
        ('51', 'B.Tech CSE'),
        ('52', 'B.Tech IT'),
        ('61', 'M.Tech CSE'),
        ('62', 'M.Tech IT'),
        ('71', 'Ph.D.'),
    )

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, related_name='student_profile')
    batch = models.IntegerField()
    branch = models.CharField(max_length=50, choices=BRANCH_CHOICES)
    course = models.ManyToManyField(Course, related_name='student_course')

    def __str__(self):
        return self.profile.user.first_name

    @property
    def roll_no(self):
        return self.profile.user.email.split('@')[0]


class Teacher(models.Model):
    class Meta:
        ordering = ('profile',)
        verbose_name = 'Teacher'
        verbose_name_plural = 'Teachers'

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, related_name='teacher_profile')
    course = models.ManyToManyField(Course, related_name='teacher_course')

    def __str__(self):
        return str(self.profile)


class Assistant(models.Model):
    class Meta:
        ordering = ('profile',)
        verbose_name = 'assistant'
        verbose_name_plural = 'assistants'

    profile = models.OneToOneField(
        Profile, on_delete=models.CASCADE, related_name='assistant_profile')
    course = models.ManyToManyField(Course, related_name='assistant_course')

    def __str__(self):
        return self.profile.user.first_name

    @property
    def roll_no(self):
        return self.profile.user.email.split('@')[0]


class Lab(models.Model):
    class Meta:
        ordering = ('number',)
        verbose_name = 'Lab'
        verbose_name_plural = 'Labs'
        unique_together = ("number", "course")

    number = models.IntegerField(default=1, validators=[
        MinValueValidator(1),
        MaxValueValidator(1000)])
    id = models.UUIDField(unique=True, default=uuid.uuid4,
                          primary_key=True)
    course = models.ForeignKey(
        Course, related_name='course', on_delete=models.CASCADE)
    start_time = models.DateTimeField(blank=True)
    end_time = models.DateTimeField(blank=True)
    description = models.CharField(
        max_length=256, help_text='Add brief Lab description', blank=True)

    def __str__(self):
        return self.lab.number + self.course.name


class Problem(models.Model):
    class Meta:
        ordering = ('id',)
        verbose_name = 'Problems'
        verbose_name_plural = 'Problems'

    id = models.UUIDField(unique=True, default=uuid.uuid4,
                          primary_key=True, editable=False)
    lab = models.ForeignKey(Lab, related_name='lab', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.TextField(blank=True)
    similar = models.FloatField(default=30)
    points = models.FloatField(default=10.0)
    correctcode = models.TextField(
        default='print("Hello World!")', blank=False)

    def __str__(self):
        return "Lab " + str(self.lab.number) + "-" + self.title


def submission_dir(instance, filename):
    return 'submissions/{0}/Lab-{1}/P{2}/{3}'.format(instance.student.roll_no, instance.problem.lab.number, instance.problem.id, filename)


class Submission(models.Model):
    class Meta:
        ordering = ('student',)
        verbose_name = 'Submission'
        verbose_name_plural = 'Submissions'
        unique_together = ("code_file", "problem")

    id = models.UUIDField(unique=True, default=uuid.uuid4, primary_key=True)
    problem = models.ForeignKey(
        Problem, related_name='problem', on_delete=models.CASCADE)
    student = models.ForeignKey(
        Profile, related_name='student', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)
    code_file = models.FileField(
        upload_to=submission_dir, help_text="Add File with proper format, so that it can be compiled")

    def __str__(self):
        return "Lab{0}-{1}-{2}".format(self.problem.lab.number, self.problem.title, self.student.roll_no)

    def filename(self):
        return os.path.basename(self.code_file.name)

landing/forms.py
import datetime
from collections import OrderedDict

from .models import Course, Lab, Profile, Teacher
from django import forms
from datetimewidget.widgets import DateTimeWidget
from django.forms.widgets import SelectDateWidget, TimeInput

from landing.models import Problem, Student, Submission


class DateInput(forms.DateInput):
    input_type = 'date'


class AddCourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddCourseForm, self).__init__(*args, **kwargs)
        fields_keyOrder = ['code', 'name', 'target_batch', 'session']
        if 'keyOrder' in self.fields:
            self.fields.keyOrder = fields_keyOrder
        else:
            self.fields = OrderedDict(
                (k, self.fields[k]) for k in fields_keyOrder)
        self.fields['name'].label = 'Course Name'
        self.fields['code'].label = 'Course Code'

        self.fields['name'].widget.attrs.update({
            'class': 'uk-input',
            'placeholder': 'Introduction to Example Technology'
        })
        self.fields['code'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
            'placeholder': 'CSX0X or ITX0X'
        })

        self.fields['target_batch'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
        })

        self.fields['session'].widget.attrs.update({
            'class': 'uk-select uk-width-auto',
            'placeholder': '20XX-XY'
        })

    class Meta:
        model = Course
        fields = {'name', 'code', 'session', 'target_batch'}


class EditCourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(EditCourseForm, self).__init__(*args, **kwargs)
        fields_keyOrder = ['code', 'name', 'target_batch', 'session']
        if 'keyOrder' in self.fields:
            self.fields.keyOrder = fields_keyOrder
        else:
            self.fields = OrderedDict(
                (k, self.fields[k]) for k in fields_keyOrder)
        self.fields['name'].label = 'Course Name'
        self.fields['code'].label = 'Course Code'

        self.fields['name'].widget.attrs.update({
            'class': 'uk-input',
        })

        self.fields['code'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
        })

        self.fields['target_batch'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
        })

        self.fields['session'].widget.attrs.update({
            'class': 'uk-select uk-width-auto',
        })

    class Meta:
        model = Course
        fields = {'name', 'code', 'session', 'target_batch'}


class AddStudentForm(forms.Form):
    roll_no = forms.CharField(max_length=9)

    class Meta:
        fields = {'roll_no'}


class AddAssistantForm(forms.Form):
    roll_no = forms.CharField(max_length=9)

    class Meta:
        fields = {'roll_no'}


class AddLabForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddLabForm, self).__init__(*args, **kwargs)
        fields_keyOrder = ['number', 'start_time', 'end_time', 'description']
        if 'keyOrder' in self.fields:
            self.fields.keyOrder = fields_keyOrder
        else:
            self.fields = OrderedDict(
                (k, self.fields[k]) for k in fields_keyOrder)

        self.fields['number'].label = 'Lab Number'
        self.fields['start_time'].label = "Start Time"
        self.fields['end_time'].label = "End Time"
        self.fields['description'].label = "Description"

        self.fields['number'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
            'placeholder': 'Eg: 2',
        })
        self.fields['description'].widget.attrs.update({
            'class': 'uk-textarea uk-input',
            'placeholder': 'Add description here',
        })
        self.fields['start_time'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
        })
        self.fields['end_time'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
        })

    class Meta:
        model = Lab
        fields = {'number', 'start_time', 'end_time', 'description'}
        dateTimeOptions = {
            'autoclose': True,
            'startDate': str(datetime.datetime.today().date()),
            'endDate': str(datetime.datetime.today().date() + datetime.timedelta(7)),
            'format': 'mm/dd/yyyy hh:ii',
        }
        widgets = {
            'start_time': DateTimeWidget(options=dateTimeOptions),
            'end_time': DateTimeWidget(options=dateTimeOptions),
        }


class AddProblemForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddProblemForm, self).__init__(*args, **kwargs)
        fields_keyOrder = ['title', 'content', 'similar', 'correctcode']
        if 'keyOrder' in self.fields:
            self.fields.keyOrder = fields_keyOrder
        else:
            self.fields = OrderedDict(
                (k, self.fields[k]) for k in fields_keyOrder)
        self.fields['title'].label = 'Problem Title'
        self.fields['content'].label = 'Problem Content'
        self.fields['similar'].label = 'Similarity Percentage'
        self.fields['correctcode'].label = 'Correct Code'

        self.fields['title'].widget.attrs.update({
            'class': 'uk-input',
            'placeholder': 'Problem - 1: Fibbonaci'
        })

        self.fields['content'].widget.attrs.update({
            'class': 'uk-input uk-textarea',
            'placeholder': 'You have ....'
        })

        self.fields['similar'].widget.attrs.update({
            'class': 'uk-input uk-textarea',
            'placeholder': 'Percentage Similarity Allowed'
        })

        self.fields['correctcode'].widget.attrs.update({
            'class': 'uk-input uk-textarea',
            'placeholder': 'Enter the correct code for the problem'
        })

    class Meta:
        model = Problem
        fields = {'title', 'content', 'similar', 'correctcode'}


class SubmissionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SubmissionForm, self).__init__(*args, **kwargs)
        self.fields['code_file'].label = 'Code File'

        self.fields['code_file'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
            'type': 'file'
        })

    class Meta:
        model = Submission
        fields = {'code_file', }


class ExtendDeadlineForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ExtendDeadlineForm, self).__init__(*args, **kwargs)
        self.fields['end_time'].label = 'Deadline'
        self.fields['end_time'].widget.attrs.update({
            'class': 'uk-input uk-width-auto',
        })

    class Meta:
        model = Lab
        fields = {'end_time'}
        dateTimeOptions = {
            'autoclose': True,
            'startDate': str(datetime.datetime.today().date()),
            'endDate': str(datetime.datetime.today().date() + datetime.timedelta(7)),
            'format': 'mm/dd/yyyy hh:ii',
        }
        widgets = {
            'end_time': DateTimeWidget(options=dateTimeOptions),
        }

landing/templates/landing/course_list.html
{% extends 'landing/base.html' %}

{% block title %}
    Labper | Courses List
{% endblock %}

{% block body %}
<div>
    <div class="uk-card-hover uk-border-rounded uk-card-default uk-card-body uk-width-1-2@m uk-margin-top uk-align-center">
    <h3 class="uk-card-title">Courses</h3>
    <hr>
    <table class="uk-table uk-table-striped">
        <thead>
            <tr>
                <th class="uk-text-center">Course Code</th>
                <th class="uk-text-center">Batch</th>
                <th class="uk-text-center">Name</th>
                <th class="uk-text-center hidden-on-small-display">Session</th>
                <th class="uk-text-center">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for course in courses %}
            <tr>
                <td class="uk-text-center">{{ course.code }}</td>
                <td class="uk-text-center">{{ course.target_batch }}</td>
                <td class="uk-text-center">{{ course.name }}</td>
                <td class="uk-text-center hidden-on-small-display">{{ course.session }}</td>
                <td class="hidden-on-small-display">
                    <a href="{% url 'leave' teacher=user.profile.teacher_profile.id course=course.code session=course.session.id %}" class="uk-width-1-1 uk-button  text-white uk-button-danger uk-width-auto uk-align-center uk-border-pill">
                        Leave
                    </a>
                </td>
                <td class="hidden-on-large-display">
                    <a uk-tooltip="title: Leave; pos:bottom;" href="{% url 'leave' teacher=user.profile.teacher_profile.id course=course.code session=course.session.id %}" class="uk-icon-button uk-button-danger uk-margin-small-right uk-text-center" uk-icon="sign-out"></a>
                </td>
            </tr>
            {% endfor %}
            
            {% for c in other_courses %}
            <tr>
                <td class="uk-text-center">{{ c.code }}</td>
                <td class="uk-text-center">{{ c.target_batch }}</td>
                <td class="uk-text-center">{{ c.name }}</td>
                <td class="uk-text-center hidden-on-small-display">{{ c.session }}</td>
                <td class="hidden-on-small-display">  
                    <a href="{% url 'teach' teacher=user.profile.teacher_profile.id course=c.code session=c.session.id %}" class="uk-width-1-1 uk-button text-white uk-button-primary uk-width-auto uk-align-center uk-border-pill">
                        Teach
                    </a>
                </td>
                <td class="hidden-on-large-display">
                    <a uk-tooltip="title: Teach; pos:bottom;" href="{% url 'teach' teacher=user.profile.teacher_profile.id course=c.code session=c.session.id %}" class="uk-icon-button uk-button-primary uk-margin-small-right uk-text-center" uk-icon="sign-in"></a>
                </td>
            </tr>
            {% endfor %}

        </tbody>
    </table>     
    </div>
</div>

{% endblock %}

landing/templates/landing/forms_default.html
{% extends 'landing/base.html' %}

{% block title %}
    Labper | {{ form_title }}
{% endblock %}

{% block body %}
{{ form.media }}
<div class="uk-card-hover uk-border-rounded uk-card-default uk-card-body uk-width-1-2@m uk-margin-top uk-align-center ">
    <h2 class="uk-modal-title uk-margin-small-top">{{ form_title }}</h2>
    <form enctype="multipart/form-data" id="signUp" class="uk-table-responsive uk-align-center" action="#" method="post">
        {% csrf_token %}
        <table class="uk-table">
            <thead>
                <tr>
                </tr>
            </thead>
            <tbody>
            {% for field in form %}
                <tr>
                    <td class="uk-text-bold">{{ field.label }}</td>
                    <td>
                        {{ field }}
                        {% if field.help_text %}
                            <p class="uk-text-warning">{{ field.help_text }}</p>
                        {% endif %}
                        {% for error in field.errors %}
                            <p class="uk-text-danger">{{ error }}</p>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <input class="uk-width-1-1 uk-button uk-button-primary uk-width-auto uk-align-center uk-border-pill" type="submit" value="{{ button }}" />
    </form>
</div>

{% endblock %}

landing/templates/landing/home.html
{% extends 'landing/base.html' %}

{% block title %}
    Labper | Dashboard
{% endblock %}

{% block body %}
    <p class="uk-text-center uk-margin-top uk-text-lead">Current Session: {{session}} </p>
    {% if user.profile.teacher_profile %}
        <div class="uk-child-width-1-3@m uk-text-center uk-grid" uk-grid>
            <div>
                <div class="uk-card uk-align-center uk-border-rounded uk-box-shadow-large uk-card-default uk-card-body">
                    <h3 class="uk-card-title">Summary</h3>
                    <hr>
                    <p>This will show recent updates</p>
                </div>
            </div>

            <div>
                <div class="uk-card uk-align-center uk-box-shadow-large uk-border-rounded uk-card-default uk-card-body">
                    <h3 class="uk-card-title">My Courses</h3>
                    <hr>
                    {% if courses %}
                    <table class="uk-table uk-table-striped uk-responsive-width">
                        <thead>
                            <tr>
                                <th class="uk-text-center">Code</th>
                                <th class="uk-text-center hidden-on-small-display">Batch</th>
                                <th class="uk-text-center hidden-on-small-display">Session</th>
                                <th class="uk-text-center">Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for course in courses %}
                            <tr uk-tooltip="title: Click to access this course; pos:right" onclick="document.location=`{% url 'course_detail' course=course.code session=course.session.id %}`" style="cursor:pointer">
                                <td>{{ course.code }}</td>
                                <td class="hidden-on-small-display">{{ course.target_batch }}</td>
                                <td class="hidden-on-small-display">{{ course.session }}</td>
                                <td>{{ course.name }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                        <p class="uk-text-center"> You have no courses :( </p>
                    {% endif %}
                </div>
            </div>
            
            <div>
                <div class="uk-card uk-align-center uk-box-shadow-large uk-card-default uk-card-body">
                    <h3 class="uk-card-title uk-border-rounded">Actions</h3>
                    <hr>
                    <a href="{% url 'list_course' %}" class="uk-text-center text-white uk-margin-small uk-border-pill uk-button uk-button-secondary">Choose Courses</a>
                    <a href="{% url 'add_course' %}" class="uk-text-center text-white uk-border-pill uk-button uk-button-secondary">Add Courses</a>
                </div>
            </div>
        </div>
    
    {% elif user.profile.assistant_profile %}
        <div class="uk-child-width-1-3@m uk-text-center uk-grid" uk-grid>
            <div>
                <div class="uk-card uk-align-center uk-border-rounded uk-box-shadow-large uk-card-default uk-card-body">
                    <h3 class="uk-card-title">Summary</h3>
                    <p class="uk-text-meta">Recent Lab</p>
                    <hr>
                    <div class="closer">
                        <p>Batch of <span class="uk-text-bold">{{ student.batch }}</span></p>
                        <p class="uk-text-bold">{{ student.get_branch_display }}</p>                    
                    </div>
                    <hr>
                </div>
            </div>
            <div>
                <div class="uk-card uk-border-rounded uk-box-shadow-large uk-card-default uk-card-body">
                    <h3 class="uk-card-title">My Courses (As TA)</h3>
                    <p class="uk-text-meta">Courses you are teaching</p>
                    <hr>
                    {% if tcourses %}
                    <table class="uk-table uk-table-striped">
                        <thead>
                            <tr>
                                <th class="uk-text-center">Code</th>
                                <th class="uk-text-center hidden-on-small-display">Batch</th>
                                <th class="uk-text-center hidden-on-small-display">Session</th>
                                <th class="uk-text-center">Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for course in tcourses %}
                            <tr uk-tooltip="title: Click to access this course; pos:right" onclick="document.location=`{% url 'course_detail' course=course.code session=course.session.id %}`" style="cursor:pointer">
                                <td>{{ course.code }}</td>
                                <td class="hidden-on-small-display">{{ course.target_batch }}</td>
                                <td class="hidden-on-small-display">{{ course.session }}</td>
                                <td>{{ course.name }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% else %}
                        <p class="uk-text-center"> You have no courses :( </p>
                    {% endif %}           
                </div>
            </div>
            
            <div class="uk-card uk-border-rounded uk-box-shadow-large uk-card-default uk-card-body">
                <h3 class="uk-card-title">My Courses (As student)</h3>
            <p class="uk-text-meta">Courses you have taken</p>
            <hr>
            {% if tcourses %}
            <table class="uk-table uk-table-striped">
                <thead>
                    <tr>
                        <th class="uk-text-center">Code</th>
                        <th class="uk-text-center hidden-on-small-display">Batch</th>
                        <th class="uk-text-center hidden-on-small-display">Session</th>
                        <th class="uk-text-center">Name</th>
                    </tr>
                </thead>
                <tbody>
                    {% for course in courses %}
                    <tr uk-tooltip="title: Click to access this course; pos:right" onclick="document.location=`{% url 'course_detail' course=course.code session=course.session.id %}`" style="cursor:pointer">
                        <td>{{ course.code }}</td>
                        <td class="hidden-on-small-display">{{ course.target_batch }}</td>
                        <td class="hidden-on-small-display">{{ course.session }}</td>
                        <td>{{ course.name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
            {% else %}
            <p class="uk-text-center"> You have no courses :( </p>
            {% endif %}
        </div>  
    
    {% else %}
        <div class="uk-text-center uk-grid" uk-grid>
            <div class="uk-width-1-3@m">
                <div class="uk-card uk-align-center uk-box-shadow-large uk-card-default uk-card-body">
                    <h3 class="uk-card-title">Summary</h3>
                    <p class="uk-text-meta">Recent Lab</p>
                    <hr>
                    <div class="closer">
                        <p>Batch of <span class="uk-text-bold">{{ student.batch }}</span></p>
                        <p class="uk-text-bold">{{ student.get_branch_display }}</p>
                    </div>
                    <hr>
                </div>
            </div>

            <div class="uk-width-2-3@m">
                <div class="uk-text-center uk-align-center uk-card uk-card-default uk-box-shadow-large uk-card-body">
                    <h3 class="uk-card-title">My Courses</h3>
                    <p class="uk-text-meta">Your enrolled courses</p>
                    <hr>
                    {% if courses %}
                    <table class="uk-table uk-table-striped">
                        <thead>
                            <tr>
                                <th class="uk-text-center">Code</th>
                                <th class="uk-text-center hidden-on-small-display">Batch</th>
                                <th class="uk-text-center hidden-on-small-display">Session</th>
                                <th class="uk-text-center">Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for course in courses %}
                            <tr uk-tooltip="title: Click to access this course; pos:right" onclick="document.location=`{% url 'course_detail' course=course.code session=course.session.id %}`" style="cursor:pointer">
                                <td>{{ course.code }}</td>
                            <td class="hidden-on-small-display">{{ course.target_batch }}</td>
                            <td class="hidden-on-small-display">{{ course.session }}</td>
                            <td>{{ course.name }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                    <p class="uk-text-center"> You have no courses :(  </p>
                {% endif %}               
                </div>
            </div>
        </div>

    {% endif %}

{% endblock %}

landing/templates/landing/ide.html
{% extends 'landing/base.html' %}
{% load static %}

{% block title %}
    Labper | IDE
{% endblock %}

{% block body %}
    <div class="sec-widget" data-widget="7af3d5ca718dc464390066d05ec6d837"></div>
    <script>
        SEC_HTTPS = true;
        SEC_BASE = "compilers.widgets.sphere-engine.com"; 
        (function(d, s, id){ SEC = window.SEC || (window.SEC = []);
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; 
            js.src = (SEC_HTTPS ? "https" : "http") + "://" + SEC_BASE + "/static/sdk/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);   
        }(document, "script", "sphere-engine-compilers-jssdk"));
    </script>

{% endblock %}